# Generated by Django 4.2.3 on 2023-07-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='rental_price_month',
            new_name='rental_price_day',
        ),
        migrations.AddField(
            model_name='book',
            name='total_rental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
